{{- if .Values.metrics.serviceMonitor.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-metrics
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  {{- with .Values.metrics.service.clusterIP }}
  clusterIP: {{ . | quote }}
  {{- end }}
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
{{- end }}
