name: Build docker image on branches
on: 
  push:
    branches-ignore:
    - main
jobs:
  build:
    name: Docker Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Docker build
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: false
